import { describe, expect, it } from "vitest";
import { authorisedBills, resolvePrincipal, scopeIsCurrent, tenancyFingerprint, tokenHash } from "./policy";
import type { LedgerAccount } from "../rent-ledger/types";
import type { Unit, Bill } from "../types";
const unit=(id="u1"):Unit=>({id,estateId:"e",unitReference:id,tenantName:"Tenant A",tenantContactName:"A",tenantEmail:"a@example.test",tenantMobile:"",status:"active",freeSupplyMeter:false,openingBalancePence:0,currentBalancePence:100,tenantAccessToken:id.padEnd(43,"x"),tenantAccessEnabled:true,createdAt:"2026-01-01"});
const account=(u:Unit):LedgerAccount=>({id:"a1",name:"A",contactName:"A",email:"",mobile:"",unitIds:[u.id],schedules:[],charges:[],payments:[],adjustments:[],audit:[],version:0,state:"active",portalEnabled:true,portalToken:"a".repeat(64),portalScope:[{unitId:u.id,tenancy:tenancyFingerprint(u)}],portalGrants:[{id:"g",unitId:u.id,tokenHash:tokenHash(u.tenantAccessToken),tenancy:tenancyFingerprint(u),billIds:["approved"],linkedAt:"2026-10-05T12:00:00.000Z",actor:"admin"}],migration:{importedAt:"",originalOpeningPence:0,suggestedOpeningPence:0,legacyThroughDate:"",warnings:[],snapshot:{}}});
describe("private-link account isolation",()=>{
  it("requires an approved link, never a unit, bill or account ID",()=>{const u=unit(),a=account(u);expect(resolvePrincipal(u.tenantAccessToken,[a],[u])?.accountId).toBe(a.id);for(const token of [u.id,a.id,"approved","x".repeat(64)])expect(resolvePrincipal(token,[a],[u])).toBeUndefined();a.portalGrants=[];expect(resolvePrincipal(u.tenantAccessToken,[a],[u])).toBeUndefined();});
  it("does not infer rent authority from unique unit membership",()=>{const u=unit(),a=account(u);a.portalScope=undefined;expect(resolvePrincipal(u.tenantAccessToken,[a],[u])).toBeUndefined();});
  it("fails closed on ambiguous account relationships",()=>{const u=unit(),a=account(u),other={...account(u),id:"other",portalEnabled:false};expect(resolvePrincipal(a.portalToken!,[a,other],[u])).toBeUndefined();});
  it("revokes direct and bill portal entry without changing bill token",()=>{const u=unit(),a=account(u);a.portalEnabled=false;expect(resolvePrincipal(u.tenantAccessToken,[a],[u])).toBeUndefined();expect(resolvePrincipal(a.portalToken!,[a],[u])).toBeUndefined();expect(u.tenantAccessToken).toBe(unit().tenantAccessToken);});
  it("replacement invalidates old direct tokens and revoked grants",()=>{const u=unit(),a=account(u),old=a.portalToken!;a.portalToken="b".repeat(64);a.portalGrants![0].revokedAt="2026-10-06";expect(resolvePrincipal(old,[a],[u])).toBeUndefined();expect(resolvePrincipal(u.tenantAccessToken,[a],[u])).toBeUndefined();expect(resolvePrincipal(a.portalToken,[a],[u])?.accountId).toBe(a.id);});
  it.each(["tenantName","tenantContactName","tenantEmail","tenantMobile","tenantAccessToken","status"] as const)("blocks both link types when %s changes",key=>{const u=unit(),a=account(u),token=u.tenantAccessToken;const changed={...u,[key]:key==="status"?"inactive":"changed"};expect(scopeIsCurrent(a,[changed])).toBe(false);expect(resolvePrincipal(token,[a],[changed])).toBeUndefined();expect(resolvePrincipal(a.portalToken!,[a],[changed])).toBeUndefined();});
  it("cannot follow a moved unit into its new tenant account",()=>{const u=unit(),a=account(u);a.unitIds=[];const b={...account(u),id:"b",portalToken:"b".repeat(64),portalGrants:[]};expect(resolvePrincipal(u.tenantAccessToken,[a,b],[u])).toBeUndefined();});
  it("limits electricity history to approved bills and newly created bills in this tenancy",()=>{const u=unit(),a=account(u);const bill=(id:string,createdAt="2026-09-01",unitId=u.id)=>({id,unitId,createdAt,issuedAt:"2026-10-06T12:00:00.000Z"} as Bill);expect(authorisedBills(a,[u],[bill("approved"),bill("old-tenant"),bill("draft-issued-late"),bill("new","2026-10-06T11:00:00.000Z"),bill("other-unit","2026-10-06","u2")]).map(b=>b.id)).toEqual(["approved","new"]);});
});
