import { beforeEach, describe, expect, it, vi } from "vitest";
import { randomUUID } from "node:crypto";
const mocks=vi.hoisted(()=>({admin:true,data:{units:[],bills:[],payments:[],billingPeriods:[],rentAccounts:[],rentAccountUnits:[],rentSettings:[],rentCharges:[],rentPayments:[],rentServices:[]} as any}));
vi.mock("next/cache",()=>({revalidatePath:vi.fn(),unstable_noStore:vi.fn()}));
vi.mock("../db",()=>({hasDatabaseUrl:()=>false,ensureSeeded:async()=>{},query:vi.fn(),transaction:vi.fn()}));
vi.mock("../data",()=>({getAppData:async()=>mocks.data}));
vi.mock("../session",()=>({requireAdminSession:async()=>{if(!mocks.admin)throw new Error("Unauthorised");return{userId:"admin"};}}));
import { createAccount, readAccounts, mutateAccount } from "../rent-ledger/store";
import { savePortalAccess, linkElectricityAccess, submitTenantQuery, updateTenantQuery } from "./actions";
import { getTenantPortal } from "./access";
import { unreadCount } from "./queries";
import type { LedgerAccount } from "../rent-ledger/types";
const current=async(id:string)=>(await readAccounts()).find(a=>a.id===id)!;
beforeEach(()=>{mocks.admin=true;});
async function setup(){await readAccounts();const id=randomUUID();const u={id,estateId:"e",unitReference:id,tenantName:"Tenant",tenantContactName:"T",tenantEmail:"",tenantMobile:"",status:"active",tenantAccessEnabled:true,tenantAccessToken:randomUUID().replaceAll("-","")+"abc",currentBalancePence:500};mocks.data.units.push(u);mocks.data.bills.push({id:`bill-${id}`,unitId:id,issuedAt:"2026-01-01",createdAt:"2026-01-01",billingPeriodId:"period"});const a:LedgerAccount={id:randomUUID(),name:"Account",contactName:"",email:"",mobile:"",unitIds:[id],schedules:[],charges:[],payments:[],adjustments:[],audit:[],version:0,state:"review",portalEnabled:false,migration:{importedAt:"",originalOpeningPence:0,suggestedOpeningPence:0,legacyThroughDate:"",warnings:[],snapshot:{}}};await createAccount(a);const form=(version:number)=>{const f=new FormData();f.set("accountId",a.id);f.set("version",String(version));f.set("enabled","on");f.set("confirmed","on");return f;};expect((await savePortalAccess(form(a.version))).ok).toBe(true);let now=await current(a.id);const f=form(now.version);f.set("unitId",id);f.set("billIds",`bill-${id}`);expect((await linkElectricityAccess(f)).ok).toBe(true);return{a:await current(a.id),u,form};}
describe("tenant query and administrator workflow",()=>{
  it("submits once, tracks unread replies and statuses, and reopens a resolved query",async()=>{const {a,u}=await setup();mocks.admin=false;const input={requestId:randomUUID(),subject:"Bill question",text:"Please check this reading",targetType:"bill" as const,targetId:`bill-${u.id}`};expect((await submitTenantQuery(u.tenantAccessToken,input)).ok).toBe(true);expect((await submitTenantQuery(u.tenantAccessToken,input)).ok).toBe(true);let q=(await current(a.id)).tenantQueries![0];expect((await current(a.id)).tenantQueries).toHaveLength(1);expect(unreadCount(q,"admin")).toBe(1);expect((await updateTenantQuery({accountId:a.id,queryId:q.id,operation:"status",status:"Resolved"})).ok).toBe(false);mocks.admin=true;expect((await updateTenantQuery({accountId:a.id,queryId:q.id,operation:"read",readCount:q.messages.length})).ok).toBe(true);expect((await updateTenantQuery({accountId:a.id,queryId:q.id,operation:"reply",requestId:randomUUID(),text:"We checked it."})).ok).toBe(true);expect((await updateTenantQuery({accountId:a.id,queryId:q.id,operation:"status",status:"In progress"})).ok).toBe(true);q=(await current(a.id)).tenantQueries![0];expect(unreadCount(q,"admin")).toBe(0);expect(unreadCount(q,"tenant")).toBe(1);expect((await updateTenantQuery({token:u.tenantAccessToken,queryId:q.id,operation:"status",status:"Resolved"})).ok).toBe(false);await updateTenantQuery({accountId:a.id,queryId:q.id,operation:"status",status:"Resolved"});await updateTenantQuery({token:u.tenantAccessToken,queryId:q.id,operation:"reply",requestId:randomUUID(),text:"One more question"});expect((await current(a.id)).tenantQueries![0].status).toBe("Open");});
  it("denies forged targets and another account's conversation",async()=>{const left=await setup(),right=await setup();const input={requestId:randomUUID(),subject:"Forged",text:"hello",targetType:"bill" as const,targetId:`bill-${right.u.id}`};expect((await submitTenantQuery(left.u.tenantAccessToken,input)).ok).toBe(false);await submitTenantQuery(right.u.tenantAccessToken,input);const q=(await current(right.a.id)).tenantQueries![0];expect((await updateTenantQuery({token:left.u.tenantAccessToken,accountId:right.a.id,queryId:q.id,operation:"reply",requestId:randomUUID(),text:"attack"})).ok).toBe(false);expect((await getTenantPortal(left.u.tenantAccessToken))?.bills.map(b=>b.id)).toEqual([`bill-${left.u.id}`]);});
  it("revokes all portal entry points and rejects writes with the old credential",async()=>{const {a,u,form}=await setup();const f=form((await current(a.id)).version);f.delete("enabled");expect((await savePortalAccess(f)).ok).toBe(true);expect(await getTenantPortal(u.tenantAccessToken)).toBeUndefined();expect(await getTenantPortal(a.portalToken!)).toBeUndefined();expect((await submitTenantQuery(u.tenantAccessToken,{requestId:randomUUID(),subject:"No",text:"no",targetType:"bill",targetId:`bill-${u.id}`})).ok).toBe(false);});
  it("blocks changed tenancies and requires replacement of previously revoked bill grants",async()=>{const {a,u,form}=await setup();u.tenantName="New tenant";expect(await getTenantPortal(u.tenantAccessToken)).toBeUndefined();expect(await getTenantPortal(a.portalToken!)).toBeUndefined();const f=form((await current(a.id)).version);expect((await savePortalAccess(f)).ok).toBe(true);const link=form((await current(a.id)).version);link.set("unitId",u.id);expect((await linkElectricityAccess(link)).ok).toBe(false);});
});
