"use client";
import { accountPath } from "@/lib/rent-ledger/links";

import { useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { approveReconciliation, previewReconciliation, allocateCredit, previewCredit, previewReceipt, recordReceipt, sendReceiptConfirmation } from "@/lib/rent-ledger/ui-actions";
import { addDays, chargeRemaining, chargesWithProjections, money, suggestAllocation, today } from "@/lib/rent-ledger/engine";
import type { LedgerAccount, PaymentInput, Receipt } from "@/lib/rent-ledger/types";
import type { ActionResult } from "@/lib/rent-ledger/errors";
import { formatMoney } from "@/lib/money";

export const inputClass = "w-full rounded-xl border border-slateLine bg-sidebar p-3 text-ink";
export const buttonClass = "rounded-xl bg-amber-400 px-5 py-3 font-bold text-slate-950 disabled:opacity-40";
async function checked<T>(promise: Promise<ActionResult<T>>): Promise<T> { const result = await promise; if (!result.ok) throw new Error(result.error); return result.value; }
type ReconcilePreview = Extract<Awaited<ReturnType<typeof previewReconciliation>>, { ok: true }>["value"];
type ReceiptPreview = Extract<Awaited<ReturnType<typeof previewReceipt>>, { ok: true }>["value"];
export function ActionForm({ action, children, className = "" }: { action: (f: FormData) => Promise<ActionResult<void>>; children: ReactNode; className?: string }) {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false); const router = useRouter();
  return <form className={className} onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); setBusy(true); setError(""); setSaved(false); try { await checked(action(f)); setSaved(true); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save."); } finally { setBusy(false); } }}><fieldset disabled={busy} className="min-w-0 space-y-3">{children}</fieldset>{busy && <p role="status">Saving…</p>}{saved && <p role="status" className="text-green-300">Saved.</p>}{error && <p role="alert" className="text-red-300">{error}</p>}</form>;
}
export function ReconciliationForm({ account }: { account: LedgerAccount }) {
  const [opening, setOpening] = useState(""); const [first, setFirst] = useState(today()); const [note, setNote] = useState("");
  const [preview, setPreview] = useState<ReconcilePreview>(); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  const input = { accountId: account.id, version: account.version, opening, first, note };
  function changed() { setPreview(undefined); setConfirmed(false); }
  return <section className="space-y-4 rounded-2xl border border-amber-500/40 bg-card p-5">
    <h2 className="text-xl font-black">Reconcile and activate</h2>
    <p>Enter the confirmed rent position through the day before new coverage begins. Positive means owed; negative means credit. Archived unit figures are preserved, but are not added to this opening balance.</p>
    <p className="text-amber-200">Unconfirmed legacy calculated balance: {formatMoney(account.migration.suggestedOpeningPence)}. This is a reference only.</p>
    {account.migration.warnings.map(w => <p key={w} className="text-sm text-mutedText">{w}</p>)}
    <label className="block">Confirmed brought-forward balance (£)<input className={inputClass} value={opening} onChange={e => { setOpening(e.target.value); changed(); }} placeholder="Enter agreed figure" /></label>
    <label className="block">First date of new rent coverage<input type="date" className={inputClass} value={first} onChange={e => { setFirst(e.target.value); changed(); }} /></label>
    <label className="block">Reconciliation source / administrator notes<textarea className={inputClass} value={note} onChange={e => { setNote(e.target.value); changed(); }} placeholder="Source of balance; agreed rate and effective date; checks completed" /></label>
    <button disabled={busy} className={buttonClass} onClick={async () => { setBusy(true); setError(""); try { setPreview(await checked(previewReconciliation(input))); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>Preview activation</button>
    {preview && <div className="space-y-3 rounded-xl border border-slateLine p-4"><p>Current outstanding: <b>{formatMoney(preview.balances.outstanding)}</b> · Unpaid overdue charges: <b>{formatMoney(preview.balances.overdue)}</b> · Unallocated credit: <b>{formatMoney(preview.balances.credit)}</b></p><p>First calculated charges (future charges remain upcoming):</p><ul>{preview.charges.filter(c => c.category !== "opening").slice(0, 8).map(c => <li key={c.id}>{c.description}: {c.periodStart}–{c.periodEnd}, due {c.dueDate}, {formatMoney(c.amountPence)}</li>)}</ul><label className="flex gap-3"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />I have checked the account, linked units, opening balance, rates, dates and partial-period rules, and approve automatic charges.</label><button className={buttonClass} disabled={!confirmed || busy} onClick={async () => { setBusy(true); setError(""); try { await checked(approveReconciliation({ ...input, confirmed })); router.refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>Sign off and activate this account</button></div>}
    {error && <p role="alert" className="text-red-300">{error}</p>}
  </section>;
}
export function PaymentForm({ account }: { account: LedgerAccount }) {
  const router = useRouter(); const charges = chargesWithProjections(account);
  const [requestId] = useState(() => crypto.randomUUID()); const [amount, setAmount] = useState(""); const [receivedDate, setReceivedDate] = useState(today()); const [method, setMethod] = useState("bank_transfer"); const [reference, setReference] = useState(""); const [creditId, setCreditId] = useState("");
  const [from, setFrom] = useState(today()); const [weeks, setWeeks] = useState("2"); const [allocations, setAllocations] = useState<Record<string, string>>({});
  const [preview, setPreview] = useState<ReceiptPreview>(); const [receipt, setReceipt] = useState<Receipt>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [complete, setComplete] = useState(false);
  const creditEntries = account.payments.filter(p => !p.reversedAt && p.receivedDate <= today() && p.amountPence > p.allocations.reduce((n, a) => n + a.amountPence, 0));
  const eligible = charges.filter(c => !c.cancelled && chargeRemaining(account, c) > 0);
  function invalidate() { setPreview(undefined); }
  function build(): PaymentInput {
    const items = Object.entries(allocations).filter(([,n]) => n).map(([chargeId,n]) => ({ chargeId, amountPence: money(n) }));
    if (items.some(x => x.amountPence < 0)) throw new Error("Allocations cannot be negative.");
    return { requestId, accountId: account.id, version: account.version, amountPence: money(amount), receivedDate, method, reference, allocations: items.filter(x => x.amountPence > 0) };
  }
  async function perform(fn: () => Promise<void>) { setBusy(true); setError(""); try { await fn(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  function suggest(selected: boolean) { try { const input = build(); const selection = selected ? { from, to: addDays(from, Number(weeks) * 7 - 1) } : undefined; const rows = suggestAllocation(account, input.amountPence, selected ? charges : charges.filter(c => c.dueDate <= today()), selection); setAllocations(Object.fromEntries(rows.map(a => [a.chargeId, (a.amountPence / 100).toFixed(2)]))); invalidate(); setError(""); } catch (e) { setError((e as Error).message); } }
  if (receipt) return <section className="space-y-4 rounded-2xl border border-green-500/40 bg-card p-5"><h2 className="text-xl font-black">Payment saved</h2><p>{formatMoney(receipt.amountPence)} received on {receipt.receivedDate}. The payment is saved independently of SMS.</p><Confirmation accountId={account.id} receipt={receipt} /><a href={`${accountPath(account.id)}`} className="underline">Return to account</a></section>;
  if (complete) return <p role="status">Credit allocation saved. <a className="underline" href={`${accountPath(account.id)}`}>Return to account</a></p>;
  return <section className="space-y-4 rounded-2xl border border-slateLine bg-card p-5"><h2 className="text-xl font-black">Record payment — {account.name}</h2><fieldset disabled={busy} className="space-y-4">
    <div className="grid gap-4 md:grid-cols-2"><label>Money source<select className={inputClass} value={creditId} onChange={e => { const id = e.target.value; setCreditId(id); const p = creditEntries.find(p => p.id === id); setAmount(p ? ((p.amountPence - p.allocations.reduce((n, a) => n + a.amountPence, 0)) / 100).toFixed(2) : ""); setAllocations({}); invalidate(); }}><option value="">New payment received</option>{creditEntries.map(p => <option key={p.id} value={p.id}>Existing credit: {p.receivedDate} · {p.reference || p.method} · {formatMoney(p.amountPence - p.allocations.reduce((n, a) => n + a.amountPence, 0))}</option>)}</select></label><label>Amount (£)<input className={inputClass} inputMode="decimal" readOnly={!!creditId} value={amount} onChange={e => { setAmount(e.target.value); invalidate(); }} /></label><label>Date received<input type="date" max={today()} className={inputClass} value={receivedDate} onChange={e => { setReceivedDate(e.target.value); invalidate(); }} /></label><label>Payment method<select className={inputClass} value={method} onChange={e => { setMethod(e.target.value); invalidate(); }}><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="other">Other</option></select></label><label className="md:col-span-2">Reference<input className={inputClass} value={reference} onChange={e => { setReference(e.target.value); invalidate(); }} /></label></div>
    <div className="flex flex-wrap items-end gap-3"><button className={buttonClass} onClick={() => suggest(false)}>Suggest oldest unpaid charges</button><label>Selected rent period starts<input className={inputClass} type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Weeks<select className={inputClass} value={weeks} onChange={e => setWeeks(e.target.value)}>{[2, 6, 12].map(n => <option key={n}>{n}</option>)}</select></label><button className={buttonClass} onClick={() => suggest(true)}>Suggest selected period</button></div>
    <p className="text-sm text-mutedText">Review and change each allocation. Selected weeks include the rent charges that overlap that date range; monthly periods remain whole charges. Money left unallocated stays account credit. Future allocated rent is prepaid coverage, not arrears.</p>
    <div className="max-h-[30rem] overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Charge / coverage</th><th>Due</th><th>Unpaid</th><th>Allocate (£)</th></tr></thead><tbody>{eligible.map(c => <tr key={c.id} className="border-t border-slateLine"><td className="p-2">{c.description}<br />{c.periodStart ? `${c.periodStart}–${c.periodEnd}` : "Brought forward / adjustment"}<span className="ml-2 text-amber-200">{c.category}</span></td><td className="p-2">{c.dueDate}{c.dueDate > today() ? " (future)" : ""}</td><td className="p-2">{formatMoney(chargeRemaining(account, c))}</td><td className="p-2"><input aria-label={`Allocation for ${c.description} due ${c.dueDate}`} className={`${inputClass} min-w-24`} inputMode="decimal" value={allocations[c.id] ?? ""} onChange={e => { setAllocations({ ...allocations, [c.id]: e.target.value }); invalidate(); }} /></td></tr>)}</tbody></table></div>
    <button className={buttonClass} onClick={() => perform(async () => { const input = build(); setPreview(creditId ? await checked(previewCredit(input, creditId)) : await checked(previewReceipt(input))); })}>Preview allocation and balance</button>
    {preview && <div className="space-y-3 rounded-xl border border-amber-500/40 p-4"><p>Resulting current outstanding: <b>{formatMoney(preview.balances.outstanding)}</b> · Unpaid overdue charges: <b>{formatMoney(preview.balances.overdue)}</b> · Unallocated credit: <b>{formatMoney(preview.balances.credit)}</b></p><p>Rent paid through: <b>{preview.paidThrough || "No continuous fully paid period from cutover"}</b>. Service charges do not extend this date.</p>{preview.covered.map(c => <p key={c.id}>Fully covered: {c.description} · {c.periodStart}–{c.periodEnd}</p>)}<p className="whitespace-pre-wrap">{preview.message}</p><button className={buttonClass} onClick={() => perform(async () => { if (creditId) { await checked(allocateCredit(build(), creditId)); setComplete(true); } else setReceipt(await checked(recordReceipt(build()))); router.refresh(); })}>{creditId ? "Confirm credit allocation" : "Save payment"}</button></div>}
  </fieldset>{error && <p role="alert" className="text-red-300">{error}</p>}</section>;
}
export function Confirmation({ accountId, receipt }: { accountId: string; receipt: Receipt }) {
  const [state, setState] = useState(receipt.confirmation?.state || "prepared"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const c = receipt.confirmation;
  if (!c) return null;
  return <div className="space-y-3"><p>SMS to account contact: <b>{c.mobile || "No number recorded"}</b></p><blockquote className="whitespace-pre-wrap rounded-xl bg-sidebar p-4">{c.message}</blockquote><p>SMS submission: {state}. Delivery: {state === "simulated" ? "not applicable (simulation)" : c.deliveryStatus || "awaiting provider report"}. Provider acceptance does not confirm handset delivery.</p>{c.error && <p>{c.error}</p>}<button className={buttonClass} disabled={busy || !c.mobile || !["prepared", "failed"].includes(state) || !!receipt.reversedAt} onClick={async () => { setBusy(true); setError(""); try { const r = await checked(sendReceiptConfirmation(accountId, receipt.id)); setState(r.state); if (r.error) setError(r.error); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{state === "failed" ? "Retry confirmation SMS" : "Send this confirmation SMS"}</button>{error && <p role="alert" className="text-red-300">{error}</p>}</div>;
}
