"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { LedgerAccount } from "@/lib/rent-ledger/types";
import type { ReconcileInput } from "@/lib/rent-ledger/reconciliation";
import { previewCalendarReconciliation, saveCalendarReconciliation } from "@/lib/rent-ledger/reconcile-actions";
import { addDays, today } from "@/lib/rent-ledger/engine";
import { formatMoney } from "@/lib/money";
import { RentCalendar } from "./calendar";
import { card, field, button } from "./views";
type Preview=Extract<Awaited<ReturnType<typeof previewCalendarReconciliation>>,{ok:true}>["value"];
export function CalendarReconciliationForm({account:a,basePath}:{account:LedgerAccount;basePath:string}) {
  const router=useRouter();const [input,setInput]=useState<ReconcileInput>({accountId:a.id,version:a.version,requestId:"",first:a.approval?.firstCoverageDate||today(),calculationFrom:"",lastPaymentDate:a.reconciliation?.lastPaymentDate||"",lastPaymentAmount:a.reconciliation?.lastPaymentAmountPence!==undefined?(a.reconciliation.lastPaymentAmountPence/100).toFixed(2):"",paidThrough:a.reconciliation?.paidThrough||"",coverageFrom:a.reconciliation?.coverageFrom||"",opening:"",reason:""});
  const [preview,setPreview]=useState<Preview>();const [confirmed,setConfirmed]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [month,setMonth]=useState(today().slice(0,7));
  function change(key:keyof ReconcileInput,value:string){setInput(i=>({...i,[key]:value,requestId:""}));setPreview(undefined);setConfirmed(false);}
  async function review(useCalculated=false){setBusy(true);setError("");const next={...input,requestId:input.requestId||crypto.randomUUID()};setInput(next);try{const result=await previewCalendarReconciliation(next);if(!result.ok)setError(result.error);else if(useCalculated&&result.value.calculation.calculatedPence!==undefined){const updated={...next,opening:(result.value.calculation.calculatedPence/100).toFixed(2)};setInput(updated);setPreview(undefined);setConfirmed(false);}else {setPreview(result.value);if(!next.opening.trim())setInput({...next,opening:(result.value.account.reconciliation!.openingPence/100).toFixed(2)});}}catch{setError("Unable to preview. Refresh and try again.");}finally{setBusy(false);}}
  return <section className={card} id="reconciliation"><h2 className="text-2xl font-black">Calendar reconciliation</h2><p>{a.state==="review"?"Confirm the opening arrears or credit through the day before new rent begins.":"Reconcile the rent account balance as at today (including services). Corrections append audited adjustments; existing receipts remain unchanged."}</p><p>Last payment details are evidence only. They do not create a receipt or establish paid-through coverage.</p><div className="grid gap-4 sm:grid-cols-2">
    <label>Last payment date (if known)<input type="date" className={field} value={input.lastPaymentDate} onChange={e=>change("lastPaymentDate",e.target.value)}/></label><label>Last payment amount (£, if known)<input className={field} inputMode="decimal" value={input.lastPaymentAmount} onChange={e=>change("lastPaymentAmount",e.target.value)}/></label>
    <label>Rent paid up to (confirmed, optional)<input type="date" className={field} value={input.paidThrough} onChange={e=>{change("paidThrough",e.target.value);if(e.target.value)change("calculationFrom",addDays(e.target.value,1));}}/></label><label>Earliest date of confirmed paid coverage<input type="date" className={field} value={input.coverageFrom} onChange={e=>change("coverageFrom",e.target.value)}/><span className="text-xs">Only confirm dates supported by your records. Earlier days remain unknown.</span></label>
    {a.state==="review"&&<><label>First date of new rent coverage<input type="date" className={field} value={input.first} onChange={e=>change("first",e.target.value)}/></label><label>Calculate historical arrears from<input type="date" className={field} value={input.calculationFrom} onChange={e=>change("calculationFrom",e.target.value)}/><span className="text-xs">Usually the day after paid-through. Actual historical schedule/rates must exist.</span></label></>}
    <label>{a.state==="review"?"Opening arrears / credit (£)":"Confirmed account balance today (£)"}<input className={field} inputMode="decimal" value={input.opening} onChange={e=>change("opening",e.target.value)}/><span className="text-xs">Positive = owed; negative = credit. Leave blank to use the suggested calculation.</span></label>
  </div>{a.state === "review" && <label className="block"><input type="checkbox" checked={!!input.deductKnownPayments} onChange={e=>{setInput(i=>({...i,deductKnownPayments:e.target.checked,requestId:""}));setPreview(undefined);setConfirmed(false);}}/> Deduct the listed historical receipts: I have checked they are not already included in the confirmed paid-through coverage. Leave unchecked when unsure.</label>}<label className="block">Evidence and manual override reason (visible on adjustments)<textarea className={field} rows={3} value={input.reason} onChange={e=>change("reason",e.target.value)} placeholder="Where the figures came from; why any override is needed"/></label><button disabled={busy} className={button} onClick={()=>review()}>Preview balance and calendar</button>
    {preview&&<div className="space-y-4 rounded-xl border border-amber-500/40 p-4"><h3 className="text-xl font-bold">Review before saving</h3><p>Balance as at {preview.calculation.asOf}: calculated <b>{preview.calculation.calculatedPence!==undefined?formatMoney(preview.calculation.calculatedPence):"Unavailable"}</b>; your confirmed amount <b>{formatMoney(Math.round(Number(input.opening)*100))}</b>.</p><p>{preview.calculation.warning}</p>{preview.calculation.calculatedPence!==undefined&&<button className="underline" onClick={()=>change("opening",(preview.calculation.calculatedPence!/100).toFixed(2))}>Use calculated balance, then preview again</button>}<details><summary className="cursor-pointer font-bold">Calculation and known payments</summary>{preview.calculation.lines.map(c=><div className="my-2" key={c.id}><p>{c.description} · {c.periodStart||c.dueDate}–{c.periodEnd||""} · {formatMoney(c.amountPence)}</p>{c.calculation?.map(x=><p className="text-xs" key={x.from}>{x.from}–{x.to}: {formatMoney(x.ratePence)} × {x.days}/{x.denominator} days</p>)}</div>)}{preview.calculation.knownPayments.map(p=><p key={p.id}>Known receipt/credit {p.date}: {formatMoney(p.amountPence)} ({a.state !== "review" || input.deductKnownPayments ? "deducted" : "not deducted"})</p>)}</details><p>After saving and catch-up: outstanding {formatMoney(preview.balances.outstanding)} · overdue {formatMoney(preview.balances.overdue)} · unallocated credit {formatMoney(preview.balances.credit)}.</p><label>Preview calendar month<input type="month" className={field} value={month} onChange={e=>setMonth(e.target.value)}/></label><RentCalendar account={preview.account} month={month} basePath={basePath} onMonthChange={setMonth}/><p>Historical rows, coverage allocations and any balance adjustment shown here will be audited. Last-payment details will not create a duplicate receipt.</p><label className="block"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I have checked the dates, coverage, rates, calculation and override reason.</label><button className={button} disabled={busy} onClick={async()=>{setError("");if(!input.reason.trim()){setError("Enter the evidence and manual override reason above, including for a £0 balance, then preview again.");return;}if(!confirmed){setError("Tick the confirmation checkbox above to confirm you have reviewed the dates and balance.");return;}setBusy(true);try{const result=await saveCalendarReconciliation({...input,confirmed});if(!result.ok)setError(result.error);else{setPreview(undefined);router.refresh();}}catch{setError("Unable to save. Refresh to check the account before retrying.");}finally{setBusy(false);}}}>{busy?"Saving reconciliation…":a.state==="review"?"Sign off and activate this account":"Confirm audited reconciliation"}</button></div>}
    {error&&<p role="alert" className="text-red-300">{error}</p>}
  </section>;
}
