import { accountPath } from "@/lib/rent-ledger/links";
import Link from "next/link";
import { formatMoney } from "@/lib/money";
import { balances, chargeRemaining, chargesWithProjections, rentCoverage, today } from "@/lib/rent-ledger/engine";
import type { LedgerAccount } from "@/lib/rent-ledger/types";

export const field = "w-full rounded-xl border border-slateLine bg-sidebar p-3 text-ink";
export const button = "inline-block rounded-xl bg-amber-400 px-5 py-3 font-bold text-slate-950";
export const card = "space-y-4 rounded-2xl border border-slateLine bg-card p-5";
export function AccountFields({ account }: { account: LedgerAccount }) { return <><input type="hidden" name="accountId" value={account.id} /><input type="hidden" name="version" value={account.version} /></>; }
export function BalanceCards({ account }: { account: LedgerAccount }) {
  const b = balances(account, today(), chargesWithProjections(account)); const coverage = rentCoverage(account);
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Current account outstanding", b.outstanding], ["Unpaid overdue charges", b.overdue], ["Upcoming unpaid · next 90 days", b.upcoming], ["Unallocated account credit", b.credit]].map(([label, amount]) => <div key={String(label)} className={card}><p className="text-sm text-mutedText">{label}</p><p className="text-2xl font-black">{formatMoney(Number(amount))}</p></div>)}</div><p className="text-sm text-mutedText">Unpaid rent charges {formatMoney(b.rent)} · Services {formatMoney(b.services)} · Brought forward {formatMoney(b.opening)}. Unallocated credit has not settled specific overdue charges. Prepayments allocated to future periods are shown against those charges.</p><p>Rent paid through: <b>{coverage.through || "Not established from allocations"}</b>{account.approval ? ` (coverage tracked from ${account.approval.firstCoverageDate})` : ""}.</p></>;
}
export function AccountsTable({ accounts }: { accounts: LedgerAccount[] }) {
  return <div className="overflow-auto rounded-2xl border border-slateLine"><table className="w-full text-left text-sm"><thead className="bg-sidebar"><tr>{["Account", "Status", "Outstanding", "Overdue unpaid", "Credit", "Paid through", ""].map(t => <th key={t} className="p-4">{t}</th>)}</tr></thead><tbody>{accounts.map(a => { const b = balances(a); return <tr key={a.id} className="border-t border-slateLine"><td className="p-4"><Link className="font-bold text-amber-200" href={`${accountPath(a.id)}`}>{a.name}</Link><p className="text-xs text-mutedText">{a.unitIds.length} linked units · {a.schedules.filter(s => s.kind === "service").length} services</p></td><td className="p-4">{a.state === "review" ? "Needs reconciliation" : a.state}</td><td className="p-4">{a.state === "review" ? "Unconfirmed" : formatMoney(b.outstanding)}</td><td className="p-4">{formatMoney(b.overdue)}</td><td className="p-4">{formatMoney(b.credit)}</td><td className="p-4">{rentCoverage(a).through || "—"}</td><td className="p-4"><Link className="underline" href={`${accountPath(a.id)}${a.state === "review" ? "#reconciliation" : "/payment"}`}>{a.state === "review" ? "Set up" : "Record payment"}</Link></td></tr>; })}</tbody></table></div>;
}
export function ChargeTable({ account, future = true }: { account: LedgerAccount; future?: boolean }) {
  const charges = future ? chargesWithProjections(account) : account.charges;
  return <div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Charge", "Coverage period", "Due", "Amount", "Allocated", "Remaining", "Status"].map(h => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{charges.map(c => <tr key={c.id} className="border-t border-slateLine"><td className="p-3">{c.description}<p className="text-xs text-mutedText">{c.category}</p>{c.calculation && <details className="text-xs"><summary>Calculation</summary>{c.calculation.map(x => <p key={x.from}>{x.from}–{x.to}: {formatMoney(x.ratePence)} × {x.days}/{x.denominator} days</p>)}<p>Partial rule: {account.schedules.find(s => s.id === c.sourceId)?.partialRule === "full" ? "full cycle; weighted across dated rates" : "daily proration; round final total"}</p></details>}</td><td className="p-3">{c.periodStart ? `${c.periodStart}–${c.periodEnd}` : "Opening / adjustment"}</td><td className="p-3">{c.dueDate}</td><td className="p-3">{formatMoney(c.amountPence)}</td><td className="p-3">{formatMoney(c.cancelled ? 0 : c.amountPence - chargeRemaining(account, c))}</td><td className="p-3">{formatMoney(chargeRemaining(account, c))}</td><td className="p-3">{c.cancelled ? "Cancelled" : c.dueDate > today() ? "Upcoming" : chargeRemaining(account, c) === 0 ? "Settled" : c.dueDate < today() ? "Overdue" : "Due today"}</td></tr>)}</tbody></table></div>;
}
export function PaymentHistory({ account }: { account: LedgerAccount }) { return <div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Received", "Amount", "Method / reference", "Allocated", "Credit", "Status"].map(h => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{[...account.payments].sort((a, b) => b.receivedDate.localeCompare(a.receivedDate)).map(p => { const allocated = p.allocations.reduce((n, a) => n + a.amountPence, 0); return <tr className="border-t border-slateLine" key={p.id}><td className="p-3">{p.receivedDate}</td><td className="p-3">{formatMoney(p.amountPence)}</td><td className="p-3">{p.method.replaceAll("_", " ")} · {p.reference}</td><td className="p-3">{formatMoney(allocated)}<details><summary>Allocation details</summary>{p.allocations.map(a => { const c = account.charges.find(c => c.id === a.chargeId); return <p key={a.chargeId}>{c?.description}: {c?.periodStart || c?.dueDate} {c?.periodEnd ? `to ${c.periodEnd}` : ""} · {formatMoney(a.amountPence)}</p>; })}</details></td><td className="p-3">{formatMoney(p.reversedAt ? 0 : p.amountPence - allocated)}</td><td className="p-3">{p.reversedAt ? `Reversed: ${p.reversalReason}` : p.legacyId ? "Opening / adjustment credit" : "Received"}</td></tr>; })}</tbody></table></div>; }
