import { beforeEach, describe, expect, it, vi } from "vitest";
import { randomUUID } from "node:crypto";
import { applyReconciliation, calculateReconciliation, type ReconcileInput } from "./reconciliation";
import { calendarDay } from "./calendar";
import { balances, projectCharges, rentCoverage } from "./engine";
import type { LedgerAccount } from "./types";
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date("2026-10-05T12:00:00Z"));});
function fixture():LedgerAccount{return{id:randomUUID(),name:"Rent",contactName:"",mobile:"",email:"",unitIds:[],state:"review",portalEnabled:false,version:0,schedules:[{id:"rent",kind:"rent",name:"Rent",frequency:"weekly",startDate:"2026-07-13",dueDay:1,timing:"advance",partialRule:"daily",enabled:true,rates:[{effectiveDate:"2026-07-13",amountPence:6500},{effectiveDate:"2026-10-05",amountPence:7000}]}],charges:[],payments:[],adjustments:[],audit:[],migration:{importedAt:"",originalOpeningPence:0,suggestedOpeningPence:0,legacyThroughDate:"",warnings:[],snapshot:{}}};}
function input(a:LedgerAccount):ReconcileInput{return{accountId:a.id,version:a.version,requestId:randomUUID(),first:"2026-10-05",calculationFrom:"2026-07-20",lastPaymentDate:"2026-07-19",lastPaymentAmount:"65",paidThrough:"2026-07-19",coverageFrom:"2026-07-13",opening:"715",reason:"11 unpaid weeks at agreed historic rate, current rate changes today"};}
describe("calendar reconciliation",()=>{
  it("calculates 11 old weeks at £65 and starts today's £70 separately",()=>{const a=fixture(),i=input(a);const calc=calculateReconciliation(a,i);expect(calc.calculatedPence).toBe(71500);expect(calc.lines).toHaveLength(11);expect(a.charges).toHaveLength(0);applyReconciliation(a,i,"admin");a.charges.push(...projectCharges(a));expect(balances(a).outstanding).toBe(78500);expect(a.payments).toHaveLength(0);expect(a.reconciliation?.lastPaymentAmountPence).toBe(6500);expect(calendarDay(a,"2026-07-15").status).toBe("paid");expect(calendarDay(a,"2026-07-21").status).toBe("overdue");expect(calendarDay(a,"2026-10-12").label).toBe("Future unpaid");expect(rentCoverage(a).through).toBe("2026-07-19");});
  it("deducts a known legacy payment once and shows a partial period",()=>{const a=fixture(),i=input(a);a.migration.snapshot={payments:[{id:"old",paymentDate:"2026-07-27",amountPence:3500}]};i.lastPaymentDate="2026-07-27";i.lastPaymentAmount="35";i.opening="680";expect(calculateReconciliation(a,i).calculatedPence).toBe(71500);i.deductKnownPayments=true;expect(calculateReconciliation(a,i).calculatedPence).toBe(68000);applyReconciliation(a,i,"admin");expect(balances(a).net).toBe(68000);expect(calendarDay(a,"2026-07-20").status).toBe("partial");expect(a.payments.every(p=>p.legacyId==="reconciliation-credit")).toBe(true);const count=[a.charges.length,a.payments.length,a.audit.length];applyReconciliation(a,i,"admin");expect([a.charges.length,a.payments.length,a.audit.length]).toEqual(count);});
  it("never applies today's rate to missing historical weeks",()=>{const a=fixture(),i=input(a);a.schedules[0].startDate="2026-10-05";a.schedules[0].rates=[{effectiveDate:"2026-10-05",amountPence:7000}];expect(calculateReconciliation(a,i).available).toBe(false);applyReconciliation(a,i,"admin");expect(balances(a).net).toBe(71500);expect(calendarDay(a,"2026-08-01").status).toBe("unknown");expect(calendarDay(a,"2026-07-15").label).toBe("Paid · reconciled");});
  it("requires an override reason and rejects stale previews",()=>{const a=fixture(),i=input(a);expect(()=>applyReconciliation(a,{...i,reason:""},"admin")).toThrow(/reason/);expect(()=>applyReconciliation(a,{...i,version:3},"admin")).toThrow(/changed/);});
  it("does not establish coverage from last payment date",()=>{const a=fixture(),i={...input(a),paidThrough:"",coverageFrom:"",lastPaymentDate:"2026-10-05",lastPaymentAmount:"1000"};applyReconciliation(a,i,"admin");expect(calendarDay(a,"2026-07-20").status).toBe("overdue");expect(rentCoverage(a).through).toBeUndefined();});
  it("uses actual rate segments in a partial period",()=>{const a=fixture(),i=input(a);a.schedules[0].rates.splice(1,0,{effectiveDate:"2026-09-30",amountPence:7000});const last=calculateReconciliation(a,i).lines.at(-1)!;expect(last.amountPence).toBe(6857);expect(last.calculation).toHaveLength(2);});
  it("reconciles live coverage through audited credits without rewriting cash receipts",()=>{const a=fixture(),i=input(a);i.opening="0";i.calculationFrom="2026-10-05";i.paidThrough="2026-10-04";applyReconciliation(a,i,"admin");a.charges.push(...projectCharges(a));vi.setSystemTime(new Date("2026-10-12T12:00:00Z"));const cash={id:"cash",requestId:"cash",accountId:a.id,amountPence:2000,receivedDate:"2026-10-05",method:"cash",reference:"",allocations:[],recordedBy:"admin",createdAt:"2026-10-05"};a.payments.push(cash);const live={...i,requestId:randomUUID(),paidThrough:"2026-10-11",opening:"0"};applyReconciliation(a,live,"admin");expect(a.payments.filter(p=>!p.legacyId)).toHaveLength(1);expect(a.payments.find(p=>p.id==="cash")?.amountPence).toBe(2000);expect(calendarDay(a,"2026-10-06").status).toBe("paid");expect(balances(a).net).toBe(0);});
  it("shows partial allocations and respects reversals",()=>{const a=fixture(),i=input(a);i.opening="0";i.calculationFrom=i.first;applyReconciliation(a,i,"admin");a.charges.push(...projectCharges(a));const c=a.charges.find(c=>c.category==="rent")!;a.payments.push({id:"p",requestId:"p",accountId:a.id,amountPence:3500,receivedDate:"2026-10-05",method:"cash",reference:"",allocations:[{chargeId:c.id,amountPence:3500}],recordedBy:"admin",createdAt:""});expect(calendarDay(a,"2026-10-05").percent).toBe(50);expect(calendarDay(a,"2026-10-05").status).toBe("partial");a.payments[0].reversedAt="2026-10-05";expect(calendarDay(a,"2026-10-05").paid).toBe(0);});
  it("requires every rent component and excludes services from calendar progress",()=>{
    const a=fixture(),i={...input(a),paidThrough:"",coverageFrom:"",opening:"0",calculationFrom:"2026-10-05"};
    a.schedules.push({...a.schedules[0],id:"extra-rent",rates:[{effectiveDate:"2026-07-13",amountPence:3000}]},{...a.schedules[0],id:"service",kind:"service",rates:[{effectiveDate:"2026-07-13",amountPence:4000}]});
    applyReconciliation(a,i,"admin");a.charges.push(...projectCharges(a));const rent=a.charges.find(c=>c.sourceId==="rent")!,extra=a.charges.find(c=>c.sourceId==="extra-rent")!,service=a.charges.find(c=>c.sourceId==="service")!;
    const p={id:"p",requestId:"p",accountId:a.id,amountPence:11000,receivedDate:"2026-10-05",method:"cash",reference:"",recordedBy:"admin",createdAt:"",allocations:[{chargeId:rent.id,amountPence:7000},{chargeId:service.id,amountPence:4000}]};a.payments.push(p);
    expect(calendarDay(a,"2026-10-05")).toMatchObject({status:"partial",total:10000,paid:7000,percent:70});expect(rentCoverage(a).through).toBeUndefined();
    p.amountPence+=3000;p.allocations.push({chargeId:extra.id,amountPence:3000});expect(calendarDay(a,"2026-10-05").status).toBe("paid");expect(rentCoverage(a).through).toBe("2026-10-11");
  });
  it("rejects reuse of a saved request with a different confirmed amount",()=>{const a=fixture(),i=input(a);applyReconciliation(a,i,"admin");expect(()=>applyReconciliation(a,{...i,opening:"1"},"admin")).toThrow(/different values/);});
});
