import Image from "next/image";
import { Home, CalendarDays, FileText, MessageCircle, LockKeyhole, Plug, ChevronRight, Download, Plus } from "lucide-react";

import { getTenantPortal } from "@/lib/tenant-portal/access";
import { balances, chargesWithProjections, chargeRemaining, rentCoverage, today } from "@/lib/rent-ledger/engine";
import { formatMoney } from "@/lib/money";
import { RentCalendar } from "@/components/rent-ledger/calendar";
import { ChargeTable, PaymentHistory } from "@/components/rent-ledger/views";
import { QueryComposer, QueryConversation } from "@/components/tenant-portal/queries";
import { InstallPortal } from "@/components/tenant-portal/install";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:{token:string}}) {return {title:"Your account | Yardle",robots:{index:false,follow:false},referrer:"no-referrer" as const,manifest:`/account/${encodeURIComponent(params.token)}/manifest.webmanifest`};}
export default async function AccountPortal({params,searchParams}:{params:{token:string};searchParams:{tab?:string;month?:string}}) {
  const p=await getTenantPortal(params.token);
  if(!p)return <main className="mx-auto max-w-lg space-y-4 p-6 text-ink"><h1 className="text-2xl font-bold">Account access is not available</h1><p>The office must confirm the electricity-to-rent account relationship, or replace an expired link. Your original electricity bill link remains separate.</p><a className="underline" href={`/bill/${encodeURIComponent(params.token)}`}>Return to electricity bill</a></main>;
  const a=p.account;const base=`/account/${params.token}`;const tab=["rent","electricity","queries"].includes(searchParams.tab||"")?searchParams.tab:"overview";const ready=a.state!=="review";
  const charges=chargesWithProjections(a);const b=balances(a,today(),charges);const rent=charges.filter(c=>c.category==="rent"&&!c.cancelled);
  const rentDebt=rent.filter(c=>c.dueDate<=today()).reduce((n,c)=>n+chargeRemaining(a,c),0)+b.opening;
  const rentOverdue=charges.filter(c=>(c.category==="rent"||c.category==="opening")&&!c.cancelled&&c.dueDate<today()).reduce((n,c)=>n+chargeRemaining(a,c),0);
  const next=rent.filter(c=>c.dueDate>=today()&&chargeRemaining(a,c)>0).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];
  const through=rentCoverage(a).through;const unread=(a.tenantQueries||[]).reduce((n,q)=>n+q.messages.slice(q.tenantReadCount).filter(m=>m.author==="admin").length,0);
  const targets=[...p.bills.map(b=>({at:b.issuedAt||b.createdAt,value:`bill:${b.id}`,label:`Electricity bill · ${p.periods.find(x=>x.id===b.billingPeriodId)?.name||b.id}`})),...a.payments.filter(p=>!p.legacyId).map(p=>({at:p.createdAt||p.receivedDate,value:`payment:${p.id}`,label:`Rent payment · ${p.receivedDate} · ${formatMoney(p.amountPence)}`})),...p.electricityPayments.map(p=>({at:p.createdAt||p.paymentDate,value:`electricity_payment:${p.id}`,label:`Electricity payment · ${p.paymentDate} · ${formatMoney(p.amountPence)}`}))].sort((left,right)=>new Date(right.at).getTime()-new Date(left.at).getTime()||left.value.localeCompare(right.value)).slice(0,5).map(({value,label})=>({value,label}));

  const electricity=p.electricityUnits.reduce((n,u)=>n+u.currentBalancePence,0);
  const dueToday=rent.filter(c=>c.dueDate===today()).reduce((n,c)=>n+chargeRemaining(a,c),0);
  const schedules=a.schedules.filter(s=>s.kind==="rent"&&s.enabled&&s.startDate<=today()&&(!s.endDate||s.endDate>=today()));
  const weekly=schedules.length>0&&schedules.every(s=>s.frequency==="weekly");
  const agreed=schedules.reduce((n,s)=>n+([...s.rates].filter(r=>r.effectiveDate<=today()).sort((x,y)=>y.effectiveDate.localeCompare(x.effectiveDate))[0]?.amountPence||0),0);
  const openQueries=(a.tenantQueries||[]).filter(q=>q.status!=="Resolved").length;
  const dateLabel=(value:string)=>new Date(value+"T12:00:00Z").toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"});
  const navigation=[{id:"overview",label:"Home",icon:Home},{id:"rent",label:"Rent",icon:CalendarDays},{id:"electricity",label:"Bills",icon:FileText},{id:"queries",label:"Messages",icon:MessageCircle}];
  const heading=tab==="rent"?"Rent":tab==="electricity"?"Electricity bills":tab==="queries"?"Messages":"";
  const messageSummary=<section className="portal-card"><div className="portal-row"><span className="portal-orb"><MessageCircle/></span><h2>Messages</h2><a className="portal-action ml-auto" href={base+"?tab=queries#new-query"}><Plus size={18}/>New query</a></div>{(a.tenantQueries||[]).length? <div className="mt-4 space-y-3">{[...(a.tenantQueries||[])].reverse().slice(0,2).map(q=><a key={q.id} className="portal-message block" href={base+"?tab=queries"}><div className="portal-row"><strong className="min-w-0 break-words">{q.subject}</strong><span className={"portal-badge ml-auto "+(q.status==="Resolved"?"is-green":"is-red")}>{q.status}</span></div><p className="mt-2 line-clamp-2 text-secondaryText">{q.messages.at(-1)?.text}</p></a>)}</div>:<p className="mt-4 text-secondaryText">No open queries. Replies from the office will appear here.</p>}</section>;
  return <main className="tenant-portal"><div className="portal-shell"><header className="portal-header"><a href={base} className="portal-brand" aria-label="Yardle home"><Image src="/yardle.png" alt="Yardle" width={640} height={200} priority className="h-auto w-full object-contain"/></a>{heading&&<h1>{heading}</h1>}<LockKeyhole aria-label="Private account" className="ml-auto shrink-0 text-secondaryText" size={19}/></header><div className="portal-content">
    {tab==="overview"&&<><div className="portal-greeting"><h1>Hi {a.contactName?.trim().split(/\s+/)[0]||a.name}</h1><p>{a.name}{p.electricityUnits.length?" · "+p.electricityUnits.map(u=>"Unit "+u.unitReference).join(", "):""}</p></div><section className="portal-card">{ready?<><div className="portal-row"><span className="portal-orb is-yellow"><Home/></span><div><h2>{rentOverdue>0?"Rent outstanding":dueToday>0?"Rent due today":"Rent balance"}</h2><p className="portal-amount">{formatMoney(rentDebt)}</p></div><span className={"portal-badge ml-auto "+(rentOverdue>0?"is-red":rentDebt>0?"is-yellow":"is-green")}>{rentOverdue>0?"Overdue":dueToday>0?"Due today":rentDebt>0?"Due":"Up to date"}</span></div><dl className="portal-stats"><div><dt>Overdue</dt><dd>{formatMoney(rentOverdue)}</dd></div><div><dt>{weekly?"Weekly rent":"Current period rent"}</dt><dd>{weekly?formatMoney(agreed):"See rent calendar"}</dd></div><div><dt>Paid through</dt><dd className="!text-sm">{through?dateLabel(through):"Awaiting confirmation"}</dd></div></dl><p className="portal-note">{next?"Next payment: "+dateLabel(next.dueDate)+" · "+formatMoney(rent.filter(c=>c.dueDate===next.dueDate).reduce((n,c)=>n+chargeRemaining(a,c),0)):"No further payment calculated in the next 90 days."}</p>{(b.credit>0||b.services>0)&&<p className="portal-note">Account credit {formatMoney(b.credit)} · Unpaid services {formatMoney(b.services)}. Credit covers rent once allocated.</p>}</>:<><h2>Rent setup in progress</h2><p className="text-secondaryText">Your rent opening balance is awaiting administrator reconciliation.</p></>}</section>
    <a href={base+"?tab=electricity"} className="portal-card portal-row"><span className="portal-orb is-green"><Plug/></span><div><h2>Electricity</h2><p>{p.electricityUnits.length?<><strong className="text-2xl">{formatMoney(Math.abs(electricity))}</strong> {electricity<0?"credit":"outstanding"}</>:"Awaiting confirmed link"}</p></div>{p.electricityUnits.length>0&&<span className={"portal-badge ml-auto "+(electricity<=0?"is-green":"is-yellow")}>{electricity<=0?"Up to date":"Outstanding"}</span>}</a>
    <div className="space-y-3">{[{label:"View rent calendar",tab:"rent",icon:CalendarDays},{label:"View bills",tab:"electricity",icon:FileText},{label:"Messages",tab:"queries",icon:MessageCircle}].map(item=><a key={item.tab} className="portal-card portal-row portal-shortcut" href={base+"?tab="+item.tab}><item.icon className="text-secondaryText"/><div><strong>{item.label}</strong>{item.tab==="queries"&&<p className="text-sm text-secondaryText">{unread?unread+" unread messages":openQueries?openQueries+" open queries":"No open queries"}</p>}</div><ChevronRight className="ml-auto text-secondaryText"/></a>)}</div><p className="portal-privacy"><LockKeyhole size={15}/>Private link · Keep it safe</p><p className="portal-note text-center">Anyone with this link can view your account. Electricity is billed separately from rent.</p><InstallPortal/></>}
    {tab==="rent"&&(ready?<><section className="portal-card"><RentCalendar account={a} month={searchParams.month} basePath={base+"?tab=rent"} compact/></section><section className="portal-card"><h2>Recent payments</h2>{a.payments.filter(p=>!p.legacyId).length?<PaymentHistory account={a}/>:<div className="portal-empty"><FileText/><p>Payments will appear here</p></div>}<a className="portal-statement" href={base+"/statement"}><Download size={19}/>View / print statement</a></section><details className="portal-card"><summary>Charges and allocations</summary><ChargeTable account={a}/></details><details className="portal-card"><summary>Dated rent and service rates</summary>{a.schedules.map(s=><div key={s.id} className="mt-3"><h3 className="font-bold">{s.name} · {s.frequency}</h3>{s.rates.map(r=><p key={r.effectiveDate}>{dateLabel(r.effectiveDate)}: {formatMoney(r.amountPence)} per cycle</p>)}</div>)}</details></>:<section className="portal-card">Rent is awaiting reconciliation.</section>)}
    {tab==="electricity"&&<><section className="portal-card"><div className="portal-row"><span className="portal-orb is-green"><Plug/></span><h2>Electricity bills</h2></div><p className="portal-note">Historical bill status. Totals include brought-forward balances; do not add them together.</p>{p.bills.map(b=><a key={b.id} className="portal-bill" href={base+"/bill/"+encodeURIComponent(b.id)}><div><strong>{p.periods.find(x=>x.id===b.billingPeriodId)?.name||"Electricity bill"}</strong><p className="text-xs text-secondaryText">Unit {p.electricityUnits.find(u=>u.id===b.unitId)?.unitReference}</p></div><strong>{formatMoney(b.roundedTotalPence)}</strong><span className={"portal-badge "+(b.paidStatus==="paid"||b.paidStatus==="credited"?"is-green":b.paidStatus==="part_paid"?"is-yellow":"is-red")}>{b.paidStatus==="part_paid"?"Partial":b.paidStatus.charAt(0).toUpperCase()+b.paidStatus.slice(1)}</span><ChevronRight size={18}/></a>)}{!p.bills.length&&<p className="portal-empty">No electricity history has been authorised yet.</p>}</section>{messageSummary}</>}
    {tab==="queries"&&<><div className="portal-row"><h2 className="text-xl font-bold">Your conversations</h2><a className="portal-action ml-auto" href="#new-query"><Plus size={18}/>New query</a></div><p className="portal-note">Messages and replies stay here in Yardle.</p>{[...(a.tenantQueries||[])].reverse().map(q=><QueryConversation key={q.id} query={q} token={params.token}/>)}{!(a.tenantQueries||[]).length&&<div className="portal-card portal-empty"><MessageCircle/><p>No conversations yet</p></div>}<div id="new-query" className="portal-compose"><QueryComposer token={params.token} targets={targets}/></div></>}
  </div><nav className="portal-nav" aria-label="Account sections">{navigation.map(item=><a key={item.id} aria-current={tab===item.id?"page":undefined} href={base+"?tab="+item.id}><item.icon size={24}/><span>{item.label}{item.id==="queries"&&unread>0?" ("+unread+")":""}</span></a>)}</nav></div></main>;
}
