
import { getTenantPortal } from "@/lib/tenant-portal/access";
import { balances, chargesWithProjections, chargeRemaining, rentCoverage, today } from "@/lib/rent-ledger/engine";
import { formatMoney } from "@/lib/money";
import { RentCalendar } from "@/components/rent-ledger/calendar";
import { ChargeTable, PaymentHistory, card } from "@/components/rent-ledger/views";
import { QueryComposer, QueryConversation } from "@/components/tenant-portal/queries";
import { InstallPortal } from "@/components/tenant-portal/install";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:{token:string}}) {return {title:"Your account | Yardle",robots:{index:false,follow:false},referrer:"no-referrer" as const,manifest:`/account/${encodeURIComponent(params.token)}/manifest.webmanifest`};}
export default async function AccountPortal({params,searchParams}:{params:{token:string};searchParams:{tab?:string;month?:string}}) {
  const p=await getTenantPortal(params.token);
  if(!p)return <main className="mx-auto max-w-lg space-y-4 p-6 text-ink"><h1 className="text-2xl font-bold">Account access is not available</h1><p>The office must confirm the electricity-to-rent account relationship, or replace an expired link. Your original electricity bill link remains separate.</p><a className="underline" href={`/bill/${encodeURIComponent(params.token)}`}>Return to electricity bill</a></main>;
  const a=p.account;const base=`/account/${params.token}`;const tab=["rent","electricity","queries"].includes(searchParams.tab||"")?searchParams.tab:"overview";const ready=a.state!=="review";
  const charges=chargesWithProjections(a);const b=balances(a,today(),charges);const rent=charges.filter(c=>c.category==="rent"&&!c.cancelled);
  const rentDebt=rent.filter(c=>c.dueDate<=today()).reduce((n,c)=>n+chargeRemaining(a,c),0)+b.opening;
  const rentOverdue=charges.filter(c=>(c.category==="rent"||c.category==="opening")&&!c.cancelled&&c.dueDate<today()).reduce((n,c)=>n+chargeRemaining(a,c),0);
  const next=rent.filter(c=>c.dueDate>=today()&&chargeRemaining(a,c)>0).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];
  const through=rentCoverage(a).through;const unread=(a.tenantQueries||[]).reduce((n,q)=>n+q.messages.slice(q.tenantReadCount).filter(m=>m.author==="admin").length,0);
  const targets=[...p.bills.map(b=>({value:`bill:${b.id}`,label:`Electricity bill · ${p.periods.find(x=>x.id===b.billingPeriodId)?.name||b.id}`})),...a.payments.filter(p=>!p.legacyId).map(p=>({value:`payment:${p.id}`,label:`Rent payment · ${p.receivedDate} · ${formatMoney(p.amountPence)}`})),...p.electricityPayments.map(p=>({value:`electricity_payment:${p.id}`,label:`Electricity payment · ${p.paymentDate} · ${formatMoney(p.amountPence)}`}))];
  return <main className="mx-auto max-w-5xl space-y-5 px-4 py-6 text-ink"><header className={card}><p className="font-bold text-amber-200">Yardle · your private account</p><h1 className="text-3xl font-black">{a.name}</h1><p>Keep this link private. Anyone with it can view this account.</p></header><nav aria-label="Account sections" className="grid grid-cols-4 gap-1 rounded-2xl bg-sidebar p-1">{["overview","rent","electricity","queries"].map(t=><a key={t} aria-current={tab===t?"page":undefined} className={`rounded-xl px-1 py-4 text-center text-xs font-bold capitalize sm:text-base ${tab===t?"bg-amber-400 text-slate-950":""}`} href={`${base}?tab=${t}`}>{t}{t==="queries"&&unread>0?` (${unread})`:""}</a>)}</nav>
    {tab==="overview"&&<><section className={card}><h2 className="text-xl font-black">Rent overview</h2>{ready?<><p className="text-2xl font-bold">{rentOverdue>0?"Rent overdue":rentDebt>0?"Rent due":"Rent up to date"}</p><dl className="grid grid-cols-2 gap-4"><div><dt>Unpaid rent and opening balance</dt><dd className="text-2xl font-bold">{formatMoney(rentDebt)}</dd></div><div><dt>Overdue rent</dt><dd className="text-2xl font-bold">{formatMoney(rentOverdue)}</dd></div><div><dt>Rent paid through</dt><dd>{through||"Not established from allocations"}</dd></div><div><dt>Next rent payment due</dt><dd>{next?`${next.dueDate} · ${formatMoney(rent.filter(c=>c.dueDate===next.dueDate).reduce((n,c)=>n+chargeRemaining(a,c),0))}`:"None calculated in the next 90 days"}</dd></div></dl><p>Unallocated account credit: {formatMoney(b.credit)} · Unpaid services: {formatMoney(b.services)}. Credit does not cover a period until allocated.</p></>:<p>Your rent opening balance is awaiting administrator reconciliation.</p>}</section><section className={card}><h2 className="text-xl font-black">Electricity · separate balance</h2><p className="text-3xl font-bold">{p.electricityUnits.length?formatMoney(p.electricityUnits.reduce((n,u)=>n+u.currentBalancePence,0)):"Awaiting confirmed link"}</p><p>Electricity is billed separately from rent.</p></section><InstallPortal/></>}
    {tab==="rent"&&(ready?<><section className={card}><RentCalendar account={a} month={searchParams.month} basePath={`${base}?tab=rent`}/></section><section className={card}><h2 className="text-xl font-bold">Charges and allocations</h2><ChargeTable account={a}/></section><section className={card}><h2 className="text-xl font-bold">Payments</h2><PaymentHistory account={a}/></section><section className={card}><h2 className="text-xl font-bold">Dated rent and service rates</h2>{a.schedules.map(s=><div key={s.id}><h3 className="font-bold">{s.name} · {s.frequency}</h3>{s.rates.map(r=><p key={r.effectiveDate}>{r.effectiveDate}: {formatMoney(r.amountPence)} per cycle</p>)}</div>)}<a className="underline" href={`${base}/statement`}>Print rent statement</a></section></>:<p>Rent is awaiting reconciliation.</p>)}
    {tab==="electricity"&&<section className="space-y-4"><h2 className="text-xl font-black">Electricity bill history</h2><p>Historical bills include brought-forward balances; do not add their totals together.</p>{p.bills.map(b=><article key={b.id} className={card}><h3 className="font-bold">{p.periods.find(x=>x.id===b.billingPeriodId)?.name} · Unit {p.electricityUnits.find(u=>u.id===b.unitId)?.unitReference}</h3><p>Total {formatMoney(b.roundedTotalPence)} · Paid {formatMoney(b.amountPaidPence)} · Remaining {formatMoney(b.remainingBalancePence)}</p><p className="capitalize">{b.paidStatus.replaceAll("_"," ")}</p><a className="underline" href={`${base}/bill/${encodeURIComponent(b.id)}`}>View this bill</a></article>)}{!p.bills.length&&<p>No electricity history has been authorised yet.</p>}</section>}
    {tab==="queries"&&<section className="space-y-4"><QueryComposer token={params.token} targets={targets}/>{[...(a.tenantQueries||[])].reverse().map(q=><QueryConversation key={q.id} query={q} token={params.token}/>)}</section>}
  </main>;
}
