import { CalendarReconciliationForm } from "@/components/rent-ledger/reconciliation-form";
import { PortalAccessPanel } from "@/components/tenant-portal/access-panel";
import { RentCalendar } from "@/components/rent-ledger/calendar";
import { accountPath, findRouteAccount } from "@/lib/rent-ledger/links";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/ui";
import { LegacyHistory } from "@/components/rent-ledger/legacy-history";
import { ActionForm, Confirmation } from "@/components/rent-ledger/forms";
import { AccountFields, BalanceCards, ChargeTable, PaymentHistory, button, card, field } from "@/components/rent-ledger/views";
import { addAdjustment, addManualCharge, addRate, reverseReceipt, saveAccountDetails, saveSchedule, setAccountState, saveAccountUnits } from "@/lib/rent-ledger/ui-actions";
import { getLedgerAccounts } from "@/lib/rent-ledger/store";
import { today } from "@/lib/rent-ledger/engine";
import { getAppData } from "@/lib/data";

import { formatMoney } from "@/lib/money";
import type { LedgerAccount, Schedule } from "@/lib/rent-ledger/types";
export const dynamic = "force-dynamic";

function ScheduleForm({ account, schedule }: { account: LedgerAccount; schedule?: Schedule }) {
  const s = schedule; const live = account.state !== "review" && !!s;
  return <ActionForm action={saveSchedule} className={card}><AccountFields account={account} /><input type="hidden" name="sourceId" value={s?.id || ""} /><h3 className="text-lg font-black">{s ? s.name : "Add rent or service schedule"}</h3><div className="grid gap-3 md:grid-cols-3">
    <label>Name<input className={field} name="name" defaultValue={s?.name} required /></label>
    <label>Charge type<select className={field} name="kind" defaultValue={s?.kind || "rent"}><option value="rent">Rent</option><option value="service">Service</option></select></label>
    <label>Frequency<select className={field} name="frequency" defaultValue={s?.frequency || "weekly"}><option value="weekly">Weekly</option><option value="monthly">Calendar monthly</option><option value="manual">Manual</option></select></label>
    <label>Start date<input className={field} name="startDate" type="date" defaultValue={s?.startDate || today()} required /></label>
    <label>End date (inclusive)<input className={field} name="endDate" type="date" defaultValue={s?.endDate} /></label>
    <label>Due/cycle day<input className={field} name="dueDay" type="number" defaultValue={s?.dueDay ?? 1} required /><span className="text-xs text-mutedText">Weekly: 0 Sun–6 Sat. Monthly: 1–31, clamped to month end.</span></label>
    <label>Payment timing<select className={field} name="timing" defaultValue={s?.timing || "advance"}><option value="advance">In advance (coverage start)</option><option value="arrears">In arrears (day after coverage ends)</option></select></label>
    <label>Partial-period rule<select className={field} name="partialRule" defaultValue={s?.partialRule || "daily"}><option value="daily">Daily proration</option><option value="full">Full cycle for partial period</option></select></label>
    {!live && <label>Initial agreed rate (£ per cycle)<input className={field} name="amount" inputMode="decimal" defaultValue={s ? (s.rates[0].amountPence / 100).toFixed(2) : ""} required /></label>}
    <label className="flex items-center gap-3"><input name="enabled" type="checkbox" defaultChecked={s?.enabled ?? true} />Enabled</label>
  </div>{live && <p className="text-sm text-mutedText">Live schedule rules and posted periods are locked. To change frequency or timing, end this schedule and add a new one. Use dated rates below for increases.</p>}<button className={button}>Save schedule</button></ActionForm>;
}
export default async function AccountPage({ params, searchParams }: { params: { accountId: string }; searchParams: { month?: string } }) {
  const accounts = await getLedgerAccounts(); const a = findRouteAccount(accounts, params.accountId); if (!a) notFound();
  const data = await getAppData(); const linked = data.units.filter(u => a.unitIds.includes(u.id));
  return <div className="space-y-6"><PageHeader title={a.name} eyebrow={`Rent account · ${a.state}`} action={a.state !== "review" ? <Link className={button} href={`${accountPath(a.id)}/payment`}>Record payment / apply credit</Link> : undefined} />
    <p>Units: {linked.map(u => u.unitReference).join(", ") || "No units attached (standalone account)"}</p>
    {a.state !== "review" && <BalanceCards account={a} />}
    <ActionForm action={saveAccountDetails} className={card}><AccountFields account={a} /><h2 className="text-xl font-black">Account contact</h2><div className="grid gap-3 md:grid-cols-2">{([['name','Account name'],['contactName','Contact name'],['mobile','Mobile for receipts'],['email','Email']] as const).map(([name,label]) => <label key={name}>{label}<input className={field} name={name} defaultValue={a[name]} required={name === "name"} /></label>)}</div><button className={button}>Save account contact</button></ActionForm>
    <ActionForm action={saveAccountUnits} className={card}><AccountFields account={a} /><h2 className="text-xl font-black">Attached units</h2><p>Link the units paid by this account. Transactions stay with this account when a unit is removed. Portal access includes electricity bills for linked units; check the payer before linking.</p><div className="grid gap-3 md:grid-cols-3">{data.units.map(u => { const other = accounts.find(x => x.id !== a.id && x.unitIds.includes(u.id)); return <label className="flex gap-2" key={u.id}><input name="unitIds" type="checkbox" value={u.id} defaultChecked={a.unitIds.includes(u.id)} disabled={!!other} />Unit {u.unitReference} {other ? `(${other.name})` : ""}</label>; })}</div><label>Reason / relationship confirmed<input className={field} name="reason" required /></label><button className={button}>Save unit membership</button></ActionForm>
    <section id="schedules" className="space-y-4"><h2 className="text-2xl font-black">Rent and service schedules</h2><p>Each schedule is independent. Due dates in arrears fall the day after coverage ends. A daily partial rule splits the charge at each rate change; the full-cycle rule charges a full amount for a partial cycle, weighted across any dated rate changes.</p>{a.schedules.map(s => <div className="space-y-3" key={s.id}><ScheduleForm account={a} schedule={s} /><div className={card}><h3 className="font-bold">Dated rate history — {s.name}</h3>{[...s.rates].sort((x,y) => x.effectiveDate.localeCompare(y.effectiveDate)).map(r => <p key={r.effectiveDate}>From {r.effectiveDate}: {formatMoney(r.amountPence)} per {s.frequency === "monthly" ? "calendar month" : s.frequency === "weekly" ? "week" : "manual period"}</p>)}<ActionForm action={addRate}><AccountFields account={a} /><input type="hidden" name="sourceId" value={s.id} /><div className="grid gap-3 md:grid-cols-3"><label>New amount (£)<input className={field} name="amount" inputMode="decimal" required /></label><label>Exact effective date<input className={field} name="effectiveDate" type="date" defaultValue={today()} required /></label><button className={button}>Add dated rate</button></div></ActionForm></div></div>)}<ScheduleForm account={a} /></section>
    {a.state === "review" ? <CalendarReconciliationForm key={a.version} account={a} basePath={accountPath(a.id)}/> : <>
      <section className={card}><h2 className="text-xl font-black">Charges and upcoming calendar</h2><ChargeTable account={a} /></section>
      {a.schedules.some(s => s.frequency === "manual" && s.enabled) && <ActionForm action={addManualCharge} className={card}><AccountFields account={a} /><h2 className="text-xl font-black">Manual period charge</h2><label>Schedule<select name="sourceId" className={field}>{a.schedules.filter(s => s.frequency === "manual" && s.enabled).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="grid gap-3 md:grid-cols-4"><label>Coverage from<input className={field} name="periodStart" type="date" required /></label><label>Coverage to<input className={field} name="periodEnd" type="date" required /></label><label>Due date<input className={field} name="dueDate" type="date" required /></label><label>Amount (£)<input className={field} name="amount" required /></label></div><button className={button}>Record manual period charge</button></ActionForm>}
      <section className={card}><h2 className="text-xl font-black">Payments and allocation history</h2><PaymentHistory account={a} />{a.payments.filter(p => !p.legacyId).map(p => <details key={p.id} className="rounded-xl border border-slateLine p-3"><summary>{p.receivedDate} · {formatMoney(p.amountPence)} · {p.reference || p.id} · {p.reversedAt ? "Reversed" : "Receipt / SMS / correction"}</summary><Confirmation accountId={a.id} receipt={p} />{!p.reversedAt && <ActionForm action={reverseReceipt}><AccountFields account={a} /><input name="paymentId" type="hidden" value={p.id} /><label>Correction reason<input name="reason" className={field} required /></label><button className={button}>Reverse this payment with audit record</button></ActionForm>}</details>)}</section>
      <ActionForm action={addAdjustment} className={card}><AccountFields account={a} /><h2 className="text-xl font-black">Audited adjustment / manual charge</h2><p>Positive adds a charge; negative creates allocatable credit. This does not claim coverage of a rent period.</p><div className="grid gap-3 md:grid-cols-3"><label>Amount (£)<input className={field} name="amount" required /></label><label>Date<input className={field} name="date" type="date" defaultValue={today()} required /></label><label>Type<select className={field} name="category"><option value="rent">Rent</option><option value="service">Service</option></select></label></div><label>Reason and affected period<input className={field} name="reason" required /></label><button className={button}>Record adjustment</button></ActionForm>
      <section className={card}><h2 className="text-xl font-black">Activation and tenant access</h2><p>Signed off by {a.approval?.actor} on {a.approval?.at}. New coverage begins {a.approval?.firstCoverageDate}. {a.approval?.note}</p><ActionForm action={setAccountState}><AccountFields account={a} /><button className={button}>{a.state === "active" ? "Pause automatic charges" : "Resume and catch up charges"}</button></ActionForm><p>Pausing stops posting; it does not end rent liability. Resume catches up missed periods. To stop rent, end its schedule.</p></section>
    </>}
    {a.state !== "review" && <details className={card}><summary className="font-bold">Reconcile balance and calendar</summary><CalendarReconciliationForm key={a.version} account={a} basePath={accountPath(a.id)}/></details>}
    <PortalAccessPanel account={a} data={data} /><section className={card}><RentCalendar account={a} month={searchParams.month} basePath={accountPath(a.id)}/></section>
    <details className={card}><summary className="font-bold">Preserved legacy history and reconciliation evidence</summary><LegacyHistory account={a} /></details>
    <details className={card}><summary className="font-bold">Account audit trail</summary>{[...a.audit].reverse().map(e => <details key={e.id}><summary>{e.at} · {e.type} · {e.actor}</summary><pre className="overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(e.detail, null, 2)}</pre></details>)}</details>
  </div>;
}
